### PR TITLE
Allow pasting in console

### PR DESCRIPTION
**Pull request by parterburn**
Proper fix for #36 for all browser types.

### CODE REVIEW

**Comment by parterburn** [comment]
@ryandao can you take a look at this one as it addresses an earlier PR of yours: #53

**Comment by ryandao** [comment]
Thanks. I'll take a look today.

**Comment by ryandao** [comment]
Hi Paul, this doesn't seem to work on Safari for me and has some weird behavior on Chrome (scroll to the bottom of the page on Cmd+v). I haven't looked into it to find out what the issue is.

**Comment by parterburn** [comment]
The code as-is doesn't work on Safari, Chrome, or Firefox for me. This CSS tweak allows it to work in Chrome & Firefox for me, but still not Safari. Can you confirm that this tweak *breaks* the paste functionality on your Safari?

I can't reproduce any weird behavior on Chrome, either. Are you seeing that without using this tweak? And if so, can you share a screenshot?

Chrome 41.0.2272.53 beta (64-bit)
Safari 8.0.3 (10600.3.18)
Firefox 35.0.1

**Comment by parterburn** [comment]
Closing for #107

**Pull request closed without merging**
