### PR TITLE
Migrate CI from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by mishina2228**
Since June 15th, 2021, the building on travis-ci.org is ceased.
This PR migrates CI from Travis CI to GitHub Actions.
Here are the details:

- Run CI on Ruby 2.7, 3.0, 3.1 and head
- Update dependencies
  - Add rack-session to Gemfile
    - rack-session is removed from rack runtime dependency.
    - Without `rack-session`, the following error occurs:
     ```
    /home/runner/work/web-console/web-console/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- rack/session/abstract/id (LoadError)
     ```
  - Remove arel from Gemfile
    - Arel is now bundled in the Active Record gem, and maintained in the rails/rails repository.
- ~`bundle exec rake templates:test` fails so far, but this PR does not address it.~
  ~I'm investigating and trying to resolve it.~
  EDIT: I've fixed it in #318.

EDIT: CI status can be seen here: https://github.com/mishina2228/web-console/actions/runs/2385207305
image

### CODE REVIEW

**Comment by gsamokovarov** [comment]
Yes! Let's test this setup and replace Travis.

**Comment by mishina2228** [comment]
> `bundle exec rake templates:test` fails so far, but this PR does not address it.
> I'm investigating and trying to resolve it.

Finally, I succeeded in fixing `bundle exec rake templates:test`.
I created #318 as another PR,. please take a look.

**Comment by mishina2228** [comment]
I rebased the branch and replaced Travis with GitHub Actions.

**Comment by gsamokovarov** [comment]
I have merged #318. Thanks for you great work on getting us to GitHub Actions! 🎉

**Pull request merged**
