### PR TITLE
Instantiate view with empty template cache

### LINKED ISSUE #303: Breaking with Rails 6.1.rc1.
Can be this change breaking web-console with rails 6.1-rc1?
Web-console:
https://github.com/rails/web-console/commit/434149617f0c2f66cda7a55206788e2713b48566#diff-7bc80c4bc731f19ccaee77fb14214df9ea0932eb1e7528085a9d517815901eceL20-R20

Rails 6.1 rc1:
https://github.com/rails/rails/commit/cd0c99c991ecbdb60b87cf648a6fddb0a50a13ad#diff-2c5bc6d4049baee92f8bb3b4cfd67b744ca0309ffbfdf6910bee8d0024ec4dffL230-R230

```
ActionController::RoutingError (No route matches [GET] "/pt/teste"):

ArgumentError: wrong number of arguments (given 2, expected 3)
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/actionview-6.1.0.rc1/lib/action_view/base.rb:230:in `initialize'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/web-console-4.0.3/lib/web_console/template.rb:20:in `new'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/web-console-4.0.3/lib/web_console/template.rb:20:in `render'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/web-console-4.0.3/lib/web_console/middleware.rb:35:in `block in call'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/web-console-4.0.3/lib/web_console/middleware.rb:17:in `catch'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/web-console-4.0.3/lib/web_console/middleware.rb:17:in `call'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/actionpack-6.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	from /Users/stephann/.rvm/gems/ruby-2.7.1@test-webtest/gems/railties-6.1.0.rc1/lib/rails/rack/logger.rb:37:in `call_app'
```
Steps to reproduce:
Raise some error on server like an not found page, or internal server error.

This is a new rails 6.1.rc1 project with this problem: https://github.com/stephannv/test-rails6-1-rc1-webconsole

### PR DESCRIPTION
**Pull request by stephannv**
Fix #303

### CODE REVIEW

**Comment by gsamokovarov** [comment]
Is this change working with Rails 6 as well?

**Comment by stephannv** [comment]
Yes @gsamokovarov , I tried with rails 6 and 6.1.rc1 and worked fine. But I don't know about older Rails versions.

**Comment by gsamokovarov** [comment]
Rails 6 support is what we're aiming for, so this is good. Thanks for the change!

**Comment by stephannv** [comment]
@gsamokovarov, I thank you for your great work maintaining this project. It's a pleasure to help.

**Pull request merged**
