### PR TITLE
Stop using Rails.logger.silence as it has been removed in version 5.0

### PR DESCRIPTION
**Pull request by MaherSaif**
Signed-off-by: Maher Saif <clever.netman@gmail.com>

### CODE REVIEW

**Comment by rafaelfranca** [comment]
As far I know it was not removed, where did you see that information?

**Comment by kaspth** [comment]
I think @MaherSaif may have been thinking of https://github.com/rails/rails/commit/481e49c64f790e46f4aff3ed539ed227d2eb46cb#diff-3c9369f9130650ede831adc1c71f9e38L107

I got stung by something similar in upgrading to sprockets-rails 3.1.1 and setting `assets.quiet = true`. When using a standard `::Logger` on Rails 4.2, it would hit the `silence` method from `Kernel::Reporting`.

**Comment by MaherSaif** [comment]
It hasn't removed from Rails - I should check before stating that.

But I have an error related to that, and here is the stack trace.

NoMethodError: undefined method `silence' for #<Logger:0x007fa36bcdba70>
  from /../2.3.0/gems/web-console-3.3.0/lib/web_console/view.rb:34:in `render'
  from /../2.3.0/gems/web-console-3.3.0/lib/web_console/template.rb:20:in `render'
  from /../2.3.0/gems/web-console-3.3.0/lib/web_console/middleware.rb:36:in `block in call'
  from /../2.3.0/gems/web-console-3.3.0/lib/web_console/middleware.rb:18:in `catch'
  from /../2.3.0/gems/web-console-3.3.0/lib/web_console/middleware.rb:18:in `call'
  from /../2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from /../2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
  from /../2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:26:in `call'
  from /../2.3.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'
  from /../2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  from /../2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
  from /../2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
  from /../2.3.0/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  from /../2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
  from /../2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/static.rb:136:in `call'
  from /../2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
  from /../2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
  from /../2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
  from /../2.3.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
  from /../2.3.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
  from /../2.3.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
  from /../2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'

**Comment by kaspth** [comment]
@MaherSaif just for fun, can you try using an instance of `AcitveSupport::Logger` and see if that helps?

**Comment by gsamokovarov** [comment]
Maybe `Rails.logger` is set to a regular `Logger` and not `ActiveSupport::Logger` in this specific app? `WebConsole.logger` delegates to `Rails.logger` during rails app init.

**Comment by MaherSaif** [comment]
Thank you guys, Rails.logger is set to Logger and not ActiveSupport::Logger.

**Pull request closed without merging**
